### ISSUE TITLE
npm install form-making -S 执行错误

### ISSUE THREAD

**Issue by itrice** [GavinZhuLei/vue-form-making#17]
执行npm install form-making -S
错误如下：
18 silly saveTree +-- vue-awesome@3.1.2
18 silly saveTree +-- vue-router@3.0.1
18 silly saveTree +-- vue-template-compiler@2.5.17
18 silly saveTree +-- vue@2.5.17
18 silly saveTree `-- vuedraggable@2.16.0
18 silly saveTree   `-- sortablejs@1.7.0
**19 verbose stack Error: Refusing to install package with name "form-making" under a package**
19 verbose stack also called "form-making". Did you name your project the same
19 verbose stack as the dependency you're installing?
19 verbose stack
19 verbose stack For more information, see:
19 verbose stack     <https://docs.npmjs.com/cli/install#limitations-of-npms-install-algorithm>
19 verbose stack     at checkSelf (D:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:64:14)
19 verbose stack     at Array.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
19 verbose stack     at LOOP (D:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
19 verbose stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:18:7
19 verbose stack     at hasMinimumFields (D:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:30:12)
19 verbose stack     at Array.<anonymous> (D:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\bind-actor.js:15:8)
19 verbose stack     at LOOP (D:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:15:14)
19 verbose stack     at chain (D:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\chain.js:20:5)
19 verbose stack     at D:\Program Files\nodejs\node_modules\npm\lib\install\validate-args.js:16:5
19 verbose stack     at D:\Program Files\nodejs\node_modules\npm\node_modules\slide\lib\async-map.js:52:35
19 verbose stack     at Array.forEach (<anonymous>)

**Comment by itrice** [comment]
安装淘宝镜像:
$ npm install -g cnpm --registry=https://registry.npm.taobao.org
然后执行
cnpm install form-making -S
